### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tony-go** [hyperdivision/vhs-tape#15]
Hi, @bcomnes :)

Inspiration of this Sunday.

Whats do you think about that : 
![VHS-TAPE](https://user-images.githubusercontent.com/22824417/62006916-8396c000-b147-11e9-8edc-4e7f484a44fb.png)

**Comment by bcomnes** [comment]
Very cool! We should add it to the readme Thanks!!

**Comment by tony-go** [comment]
UPDATE : 

![VHS-TAPE-2](https://user-images.githubusercontent.com/22824417/62011836-2f5b0280-b17e-11e9-814f-80af07d01230.png)

**Comment by bcomnes** [comment]
Added it to the readme. Looks great!

**Comment by bcomnes** [comment]
So cool man! I love it. Thank you so much for making this :)

One idea: any idea how to make the box edges look beat up like what all vhs boxes end up like?

![ddab73b962440d79d45d4d3c6de43cd6](https://user-images.githubusercontent.com/166301/62032020-f146f880-b1e8-11e9-9b39-e4b644640915.png)


![71bd52063204f7b072a673d85dcf98dc](https://user-images.githubusercontent.com/166301/62031953-c78dd180-b1e8-11e9-94c8-e3f10737b435.jpg)

![file_77de2d6125_400w](https://user-images.githubusercontent.com/166301/62031957-ca88c200-b1e8-11e9-9c2e-0463f9d73fd3.jpg)

**Comment by tony-go** [comment]
Im trying to get something ;)

**Comment by tony-go** [comment]
![VHS-TAPE-3](https://user-images.githubusercontent.com/22824417/62077629-d907c580-b24a-11e9-9b5e-6979aea65cd8.png)

I can change color if you want ? or make something more dusty.

I can start a new creation based on this 

<img width="634" alt="Capture d’écran 2019-07-29 à 23 59 14" src="https://user-images.githubusercontent.com/22824417/62085877-f6de2600-b25c-11e9-9ad5-eb6bd67f56c1.png">

Let me know what you prefer :)

**Comment by bcomnes** [comment]
Love it!  

> I can start a new creation based on this

Nah unless you feel like it.   I just needed a visual, its hard to describe a texture ;)

**Comment by bcomnes** [comment]
![EA0veyCW4AErhTj](https://user-images.githubusercontent.com/166301/62378580-66962e80-b545-11e9-883a-eb006f4a7314.png)

Capturing for history ✌️ 

The box distress looks a little better I think, but I also prefer the icon-y vhs tape in the original better than the realistic tape.  Looks kinda creepy 🤔 

If you feel like iterating on this some more here are some ideas I have:

- Could we sort of replicate the [VHS] logo like [VHS-Tape] or something?   Not sure if this is a good idea or not.

![download](https://user-images.githubusercontent.com/166301/62378813-ede3a200-b545-11e9-90ef-ba628feb5d4b.png)

 I found a similar font: https://www.fontyukle.net/en/DownLoad-Lester+Bold.ttf

- I like the icony look, lets go for that over realism.

- The font courier looks off. I feel like VHS tapes used more of a sans font.

![VHSCassetteBlank-40](https://user-images.githubusercontent.com/166301/62378953-326f3d80-b546-11e9-957c-f55a15c47fba.jpg)

![VHS](https://user-images.githubusercontent.com/166301/62378958-3602c480-b546-11e9-83fd-b554997abe7a.png)

![tumblr_np4qkmGKGV1usyxujo1_1280](https://user-images.githubusercontent.com/166301/62378964-38fdb500-b546-11e9-80fc-059a253084bc.jpg)

- The muted fall color rainbow is on point, obviously :V

**Comment by tony-go** [comment]
Hi @bcomnes ,

Thanks for your feedback :) 

Here two a new flat version of the logo. I add some touch of texture, but not too much because I think that mixing flat and texture are not very good.

![VH2-LOGO-3](https://user-images.githubusercontent.com/22824417/62420894-285e5380-b69a-11e9-8f88-7676ae7ebbdd.png)

![VH2-LOGO-4](https://user-images.githubusercontent.com/22824417/62420974-1b8e2f80-b69b-11e9-96c7-97b211488013.png)

I'll change for "raindow" color after :)

**Comment by bcomnes** [comment]
Love it! :V

**Comment by tony-go** [comment]
:) Im gonna update the color as "Rainbow" tape, and send you a new version :)

**Comment by tony-go** [comment]
New version :) 

![VH2-LOGO-5](https://user-images.githubusercontent.com/22824417/62730546-766bb200-ba20-11e9-9149-9719ac3f7879.png)

![VH2-LOGO-5-2](https://user-images.githubusercontent.com/22824417/62736040-cd778400-ba2c-11e9-8133-7e0d1339f56a.png)

**Comment by bcomnes** [comment]
This is the best version yet.  Red has better contrast. 🙏😻

**Comment by tony-go** [comment]
Happy to read :) I add the red one to the readme so ? :)

**Comment by bcomnes** [comment]
Yeah!

**Comment by bcomnes** [comment]
@tony-go can you PR the source assets to the repo?  We can have it live here in case we need to generate any other assets from it down the road.

**Comment by tony-go** [comment]
Done :) @bcomnes
