### ISSUE TITLE
Add some tooling suggestions

### ISSUE THREAD

**Issue by bcomnes** [hyperdivision/vhs-tape#17]
It may not be totally obvious to newcomers how to run a cjs bundle easily so it would be nice to expand with some runnable examples in the following environments:

- budo
- tape-run
- nanotron

**Comment by tony-go** [comment]
Maybe, we can add three command line example in the 'README.md' for each of theme running `example.js` ?

For example : 
```bash
budo --live --open example.js
```

**Comment by bcomnes** [comment]
Yeah perfect

**Comment by tony-go** [comment]
I'll do it in the day :)

**Comment by bcomnes** [comment]
This is done!
