### ISSUE TITLE
Add pre-run script for css and sprites

### ISSUE THREAD

**Issue by bcomnes** [hyperdivision/vhs-tape#18]
Many apps bootstrap a lot of shared resources:

- A global style sheet
- A sprite-sheet
- something else? 

You should be able to configure a pre-run script to run once in front of all tests.

**Comment by tony-go** [comment]
For style sheet, I imagine something like : 
```javascript
const vhs = require('vhs')

vhs.setStyle('../stylePath.css')
vhs.setSprite('../path')
```

Maybe it's not exactly what you ask for ?

**Comment by emilbayes** [comment]
It would be cool to have this on the assert handle also so I could do:

```js
test('my component', function (assert) {
  assert.sprites('../button-icons.svg')
  assert.styles('../button.css')

  // ...
}}
```

**Comment by tony-go** [comment]
> It would be cool to have this on the assert handle also so I could do:
> 
> ```js
> test('my component', function (assert) {
>   assert.sprites('../button-icons.svg')
>   assert.styles('../button.css')
> 
>   // ...
> }}
> ```

Seems good to me :)

I'll try something :)

**Comment by bcomnes** [comment]
You can sort of do that now with

```js
assert(t.element.querySelector(`#some-assumed-element`)
```

Maybe we do something like 

```js
t.querySelector('foo')
// Or
t.querySelector(someElement) // Asserts element is in t.element or document?
```

And you can get the querySelector shortcut coupled with an assertion, similar to the other assertion helpers.

The thing I wanted to accomplish, here was avoiding having to import the global styles into every test.

```js
const css = require('hui/css')
const vhs = require('vhs-tape')
css('../../app.css')
// ...
```

The problem here is that if you run multiple vhs-tape tests, the global requires are getting required very time, possible inserting global css again and again. 

VHS should remain similar to tape, in that its just a library.  Perhaps this is a concern for the runner cli? Or maybe a transform?  Maybe set a field in package.json like:

```js
"vhs": {
  "global-script": "./global-setup.js"
}
```

And then when you run a tape file with the helper test runner cli it picks this up.  Or maybe its a transform?

The other possible implementation: vhs exports a global loader method:

```js
const vhs = require('vhs-tape')

vhs.global(__dirname, '../../global-stuff.js')
```

Each file that wants global stuff would have to declare its global deps (a good thing), but when run together in a single page, VHS would de-dupe calls to the same files by keeping track of which files were were already called.  Internally, this would just require files when they haven't been required before yet. 

This would probably be easiest, and not introduce any additional config concepts.

**Comment by bcomnes** [comment]
Or maybe just having a global setup file, and requiring that everywhere would do the de-duping now that I think about it. This way, it would just be a pattern, rather than duplicating mechanics for a specific context.

**Comment by bcomnes** [comment]
Closing.  If you need one-off global style sheets or sprites loaded, create a global style file and load it into all of your tests.  Module loading will de-dupe it, and your tests retain specify their dependencies.

**Comment by tony-go** [comment]
I started something like that in package.json
```
"vhs": {
    "style": "./style.css"
}
```

I stop for now :) let me know if you closing or not ;)

**Comment by bcomnes** [comment]
I think we should hold off working on a config based solution for now and get some real world experience with the idea I added to the readme last night.

If that works well, it’s a lot of code we don’t have to write and maintain.

**Comment by bcomnes** [comment]
If people come across serious problems with that approach then reopen a new issue and describe them. I’m thinking this might be in the domain of the bundler if it does end up needing new code.

**Comment by tony-go** [comment]
You're right :)
