### ISSUE TITLE
Add slow method

### ISSUE THREAD

**Issue by bcomnes** [hyperdivision/vhs-tape#9]
`vhs.slow('test', async t => {}) === vhs.delay(500)('test', async t => {})` or something

**Comment by tony-go** [comment]
I tried something but I got this error running test script :
![Capture d’écran 2019-07-26 à 17 59 38](https://user-images.githubusercontent.com/22824417/61964866-3db6ec00-afcf-11e9-914a-a2310193037a.png)
FYI I got the same error when I tried `vhs.delay(500)('test', async t => {})`

**Comment by bcomnes** [comment]
Can you post a full example?

**Comment by tony-go** [comment]
@bcomnes can you check the pull request #12 ?

**Comment by bcomnes** [comment]
Ah cool sorry didn't see that on my phone.  I think I spotted an error.  Left my note in a review.

**Comment by bcomnes** [comment]
This is done 🙌
